# Generated by Django 5.0.4 on 2024-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(default='images/default.jpg', upload_to='static/images'),
        ),
    ]
