# Generated by Django 5.0.4 on 2024-04-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fimage-coming-soon&psig=AOvVaw2MFl0qv7Tb_--KmQ17Fh21&ust=1713129611626000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCJDz56CPwIUDFQAAAAAdAAAAABAE'),
        ),
    ]
