# Generated by Django 5.0.4 on 2024-04-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_preptime',
            field=models.IntegerField(default=0),
        ),
    ]
